### ISSUE TITLE
Release version 5.0.0

### ISSUE THREAD

**Issue by sksat** [ut-issl/s2e-core#122]
## Overview
Major version update

## Details
Write in detail.

## Conditions for close
- [x] #85
- [x] #87 
- [x] #53
- [x] https://github.com/ut-issl/s2e-documents/issues/29
- [x] Release `v5.0.0`

## Supplement
Write additional comments if you need.

## Note
- If there are related Projects, tie them together.
- Set `priority` label if possible.
- Assignees should be set if possible.
- Write a conclusion when closing the issue.

**Comment by 200km** [comment]
@sksat ドキュメントでv5.0.0をリファーしたいことが多々あるので、リリースしてしまってからドキュメントを修正したほうが良い気もしてきたのですが、どうでしょう？

**Comment by 200km** [comment]
それとも、URLは`https://github.com/ut-issl/s2e-core/releases/tag/v5.0.0`で確定だからそれを使えば良いですかね。

**Comment by sksat** [comment]
すみませんメンション見てませんでした．とりあえずURLはそれで確定なのでPRを作っておいて同じようなタイミングでマージ，でよさそうです

**Comment by 200km** [comment]
リリースされたのでCLOSE!!

https://github.com/ut-issl/s2e-core/releases/tag/v5.0.0
