### ISSUE TITLE
build error when USE_HILS ON

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/s2e-core#134]
## Overview
build error when USE_HILS ON

### Description
build error
`コマンド ライン error D8016: コマンド ライン オプション '/clr' と '/MT' は同時に指定できません`

### Conditions of occurrence
USE_HILS is set to ON

###  Additional information
NA

## Task
- [ ] Fix compile option

## Scope of influence
HILS

## Supplement
NA

## Note
NA

**Comment by seki-hiro** [comment]
@200km 
HILSで必要なc++/cliをコンパイルするための[/clr](https://docs.microsoft.com/ja-jp/cpp/build/reference/clr-common-language-runtime-compilation?view=msvc-170)オプションと/MTオプションとを[同時には使えない](https://docs.microsoft.com/ja-jp/cpp/build/reference/clr-restrictions?view=msvc-170)ようです。

common.cmakeの/MTオプションをコメントアウトするとビルドできるのですが、このオプションは何のためにあるか教えていただけないでしょうか？

**Comment by 200km** [comment]
HILSまで見てませんでしたね、、、warningを消すために追加したオプションですが、HILS ONのときは消したほうが良さそうですかね。

**Comment by 200km** [comment]
hotfix出す必要がありそうですね。

**Comment by seki-hiro** [comment]
hotfixの方法がわからなかったのですが、ローカルではdevelopからしかブランチを切れないという理解であってますでしょうか？hotfixというのはmasterからの分岐を指しますか？
