### ISSUE TITLE
Avoid namespace collision of Vector and Matrix class

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#24]
## Overview
Avoid namespace collision of Vector and Matrix class.

## Details
When users want to use Eigen, the namespace collision happens with `Vector` and `Matrix` which are the S2E internal library.  
We need to remove `using namespace libra` or rename the libraries.

## Conditions for close
When the collision is resolved.

## Supplement
NA

## Note
- Write a conclusion when closing the issue.

**Comment by 200km** [comment]
@suzuki-toshihir0  こちら、既にほぼすべてのヘッダファイルから`using namespace libra`は無くなっていました。残っていたのは使われていない古いコンポーネントのヘッダのみでしたが、それも　#109　で消しました。  
これでCLOSEで良いですかね？

**Comment by suzuki-toshihir0** [comment]
はい，問題ないと思います．#109もapproveしました．

**Comment by 200km** [comment]
では、CLOSEします。
