### ISSUE TITLE
Add ideal torque generator

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#247]
## Overview
Add ideal torque generator

## Details
Add the ideal torque generator as a component.  
The [ForceGenerator](https://github.com/ut-issl/s2e-core/blob/develop/src/Component/IdealComponents/ForceGenerator.hpp) is a reference example.

## Conditions for close
- The component class is implemented and tested.

## Supplement
NA

## Note
担当: @kai0722

**Comment by 200km** [comment]
@kai0722 Detailsにも書いていますが、[ForceGenerator](https://github.com/ut-issl/s2e-core/blob/develop/src/Component/IdealComponents/ForceGenerator.hpp)のトルク版を作るというのが作業内容となります。ForceGeneratorをざっと眺めてみて質問があればまず質問してみてください。

**Comment by kai0722** [comment]
ざっと見てみたところ，ForceGeneratorのForce部分をTorqueに変えれば良さそうに思えたのですが，Torque特有の変更点・追加点はありますか？

**Comment by 200km** [comment]
@kai0722 確認ありがとうございます。torque特有の部分は無い気はしています。もし実装していて出てきたら相談しましょう。
