### ISSUE TITLE
Copy initialize functions for `SensorBase` in `S2E-FF`

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#250]
## Overview
Copy initialize functions for `SensorBase` in `S2E-FF`

## Details
The target file is in [here](https://github.com/ut-issl/s2e-ff/tree/develop/s2e-ff/src/Components/Abstract).

## Conditions for close
- The files are copied.

## Supplement
NA

## Note
NA

**Comment by sksat** [comment]
FYI: URLs such as `https://github.com/<org>/<repo>/tree/develop/hogehoge` are not recommended as the content they point to may change; you can press the 'y' key in the GitHub web UI to get a permanent link.
