### ISSUE TITLE
Minor refactor of `Disturbance`

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#261]
## Overview
Minor refactor of `Disturbance`

## Details
Codes of `Disturbance` are not easy to read since they are old.  
We need minor refactor to improve the readability.

## Conditions for close
- The codes are refactored

## Supplement
NA

## Note
NA

**Comment by LilKoke** [comment]
@200km こちら具体的にはどのようなリファクタを考えていますでしょうか？

**Comment by 200km** [comment]
こちらは命名の修正などですが、下記のmajor_updateの中でやってしまうので、他のが良いかも知れません。

https://github.com/ut-issl/s2e-core/pull/303

**Comment by LilKoke** [comment]
承知しました。
