### ISSUE TITLE
Refactor GNSSReceiver

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#276]
## Overview
Refactor GNSSReceiver

## Details
GNSSReceiver class has a lot of assumption to simplify.  
We can implement more detailed model using GnssSatellite class.

64bit buildで生じるwarningsも消す。

Also, add `time delay effect` into the GNSS observation.

## Conditions for close
- Refactored

## Supplement
NA

## Note
NA

**Comment by LilKoke** [comment]
@200km こちらのissue興味があるのでどのようなモデルを利用するのかなどの追加の説明をお願いいたします。

**Comment by 200km** [comment]
こちらはちょっとまだ明確な方針は決まっていない状態ですね。少し考えさせてください。

**Comment by LilKoke** [comment]
了解しました。
