### ISSUE TITLE
Decide Coding rules

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#33]
## Overview
Decide Coding rules

## Details
The coding rule for S2E is described [here](https://github.com/ut-issl/s2e-documents/blob/main/General/CodingConvention.md), but the rule is unsophisticated.  
We need to change it better and more general for programmers.

## Conditions for close
When the coding rule is decided.

## Supplement
NA

## Note
NA

**Comment by 200km** [comment]
今までずっと放置してしまっていましたが、手を付けなければと思い、issueを立てました。

@sksat コード規約やスタイルについて特段強い意見は無いのですが、どういう風にしたら良いかアドバイスいただけると嬉しいです。

**Comment by sksat** [comment]
C++ですし既存のスタイルに載っかってしまうのが楽ですね．`clang-format`とかでフォーマットできますし．
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options

**Comment by 200km** [comment]
ありがとうございます！その方針で行きたいと思うのですが、リンク先に書かれているLLVM,Googleなどからベースとなるスタイルを選ぶという感じでしょうか？おすすめはありますか？

@meltingrabbit C2Aは何をベースにしていましたっけ？できる限り近いのが良いかなと思っているのですが。

**Comment by meltingrabbit** [comment]
clang-formatでGoogleルールを当てようとして，（C++ではなくpure Cなので）しんどいなぁとなって止まってます．

とはいえGoogleルールは定数などのルールが個人的にはあまり好きではない感じです．

ちょっとお待ち下さいね．

**Comment by sksat** [comment]
C2Aと合わせた方がいいかもしれないというのはたしかにありそう．僕もあんまりちゃんとそれぞれのコーディングスタイルについてちゃんと把握できてないので確認してみてます．ただ個人的にはGoogleのスタイルはあんまり好きじゃないですね...(一番好みが分かれるスタイルでもある)．

**Comment by meltingrabbit** [comment]
過去のメモみて思い出しました．

gnuは

![image](https://user-images.githubusercontent.com/39541984/149110155-e489bc83-6eb1-45ca-be37-70bed4bb6041.png)


が，個人的にはつらかったのでやめました．

LLVMはallman styleじゃなかった（C2Aは元来allmanなので）のでやめて，googleにした，という経緯です．


とはいえ，C2AはC++移行までは現状の  
https://github.com/ut-issl/c2a-core/blob/99b697d6733251f1599b561a03602892c5da115b/Script/CI/check_coding_rule.py  
でいくしかないかなぁとは思ってます．

そしてそれはそれなりに先のことなので，一旦C2Aを無視してもいいかもです．（なので，現状はgoogleに近くはあります）

**Comment by meltingrabbit** [comment]
google styleでだいたい固めて，受け入れがたい部分は，個別設定（clang-formatの設定でできる）するというのもなしではないですが，その議論がめんどくさいというのもあります．

**Comment by sksat** [comment]
GoogleのスタイルはあくまでC++のスタイルであってかなりC++に関するものが多い(そしてそこの好みがめちゃくちゃ分かれる)ので，S2EがC++である以上もうちょい慎重になりたいかもです．あとC2Aと合わせる云々はインデント関連とか命名規則とかぐらいでいい気もします．

**Comment by meltingrabbit** [comment]
> あとC2Aと合わせる云々はインデント関連とか命名規則とかぐらいでいい気もします．

そうね．どうせ今後プロセス分離するなら，スタイルそのものを合わせる必要はないかも．（そもそも性質が違いすぎるので）

**Comment by 200km** [comment]
個人的にはC2Aとあまりに違うスタイルは両方一緒に書いているときとかに混乱してしまうので、C2Aと近いといいなとは思っています。  が、気になるのは主にはインデントとかの話なので、`C2Aと合わせる云々はインデント関連とか命名規則とかぐらい`でいいと思います。

**Comment by 200km** [comment]
その上で何かしらベースは決めないといけないのだろうと思いますが、どう決めていきましょうか。

**Comment by meltingrabbit** [comment]
期限決めて各々スタイル眺めて，これがいいなぁと出し合うしかない気がします（好みなので）

C2Aに関しては，安全性の理由から修正してますが，こういうのをどうするかは別途議論してもいいかもです．

例
- https://github.com/ut-issl/c2a-core/blob/99b697d6733251f1599b561a03602892c5da115b/Docs/General/CodingRule.md#L447-L452
- https://github.com/ut-issl/c2a-core/blob/99b697d6733251f1599b561a03602892c5da115b/Docs/General/CodingRule.mdL474-L477

**Comment by meltingrabbit** [comment]
あと，命名については，別途議論が必要かと思います．C2A踏襲してもいいですし，別途変えてもいいと思います．

特に，単位系などは，別で進んでるかもですが，型に押し込める方法で行きたいので，C2Aを踏襲したくない気持ちが強いです（C++なので）

**Comment by 200km** [comment]
はい。全て決めるの時間かかりそうなので少しずつ決めていきたいですね。
まずは、インデントなどから決めて、きれいにして行きたいなと思います。

命名の単位系は方に押し込める方針で良いと思いますが、それができるまではどうするかと言うのは決めたい気はしています。

**Comment by sksat** [comment]
あとはとりあえず最低限欲しいものを上げていくのもありますね．個人的には
- `using namespace`のヘッダでの使用禁止(ヘッダ以外でも大きなスコープでは非推奨．特に`std`は．)
- 例外の使用禁止

は入れたいですね．

**Comment by meltingrabbit** [comment]
上に加えて個人的に入れてほしいのは，

- インデントはスペースがいい（まあ4でいいのではと思う）
- メタコメント
  - https://github.com/ut-issl/c2a-core/blob/99b697d6733251f1599b561a03602892c5da115b/Docs/General/CodingRule.md?plain=1#L823-L827

ぐらいですかねぇ．

- CのenumではなくC++の使いましょうとか，適当な配列で頑張らずにSTLとかコンテナ使いましょうとか，そういう指針はあってもいいかもしれない？ とか？

C2Aの規約見てましたが，細かい話は，まず参照するスタイル選んでから出ないと議論できないので．

**Comment by 200km** [comment]
> インデントはスペースがいい  
たぶんこれは最近書いたのはスペース2つになっていると思います(現行ルールにもそう書いているので)  
名前がつくまえのむちゃくちゃ古いものや、外部から取ってきているものがそうなっていないという感じですかね。

他はOKです。

>まず参照するスタイル選んでから

**Comment by meltingrabbit** [comment]
> インデント

ごめんなさい，ボケてました，2がいいです．（C2Aも2ですし）

**Comment by meltingrabbit** [comment]
@sksat 参照するスタイル選び，どっかで時間決めてガット話します？

**Comment by sksat** [comment]
> @sksat 参照するスタイル選び，どっかで時間決めてガット話します？

よさそう．それでお願いします．

**Comment by 200km** [comment]
時間合えば僕も参加しますが、優先度低めでいいです。

**Comment by meltingrabbit** [comment]
- https://github.com/ut-issl/s2e-core/pull/35
- https://github.com/ut-issl/s2e-core/pull/36

をみて，low-level issueはどっちも同じなので，あまり関係はなく，あとはネーミングルールをどっちベースにするか，なきがしますね．

**Comment by meltingrabbit** [comment]
LLVMのネーミングルールに手動で直すのめっちゃ大変そうなので，googleのフォーマットでいいのでは？という気持ちになってきた．

**Comment by meltingrabbit** [comment]
C2Aの設定，一応貼っておきますね．

https://gist.github.com/meltingrabbit/40869b30a0863fa89fe392cf7840cd10

**Comment by sksat** [comment]
ビルドCIも入りましたし，#35 をベースに`.clang-format`を拵えてフォーマットかけるやつどこかでガッとやってしまいます？

**Comment by sksat** [comment]
clang-formatはネーミングルールまでは口田してこないようなので，少なくともclang-formatのベースはGoogleでよさそうです．ネーミングルールに関する強制(CIでチェックして落とすとか)は別の仕組みでやろうかな，と思っています．

**Comment by 200km** [comment]
分かりました！その方針で賛成です。

**Comment by sksat** [comment]
1行の最大文字数を150文字に: #70

**Comment by meltingrabbit** [comment]
@sksat これ実はcloseできる？

**Comment by 200km** [comment]
どこまでをcoding ruleと呼ぶかというのもありますが、今決まっているのはフォーマットだけで、命名規則などは決まっていないのかなと思っています。一度これをCLOSEして、別issue立ててもいいとも思います。

**Comment by sksat** [comment]
一旦閉じてよさそう

**Comment by 200km** [comment]
では、CLOSEしましょうか。
