### ISSUE TITLE
enumのnaming ruleを全て確認する

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#336]
## Overview
enumのnaming ruleを全て確認する

## Details
いま、ほとんどGoogle Style guideにあっていない

https://ttsuki.github.io/styleguide/cppguide.ja.html#Function_Names

## Conditions for close
- 全部修正したら
- 
## Supplement
NA

## Note
NA

**Comment by sksat** [comment]
このルール，scoped enum に対しては頓珍漢だったりもしますし，現状がほとんど合っていないのであれば，無理に Google Style に合わせず S2E の規約に明示すればいいかなとも思いますね．

**Comment by 200km** [comment]
v5までのS2Eは何もルールが無く、`kHogeFuga`も`HOGE_FUGA`も混ざっていたので、とりあえずは何かに合わせたく、Google Styleに合わせたいなと思ってます。

**Comment by 200km** [comment]
Done
