### ISSUE TITLE
plot_satellite_orbit_on_miller,py might have bug

### ISSUE THREAD

**Issue by DaikiTsuzuki** [ut-issl/s2e-core#405]
## Overview
plot_satellite_orbit_on_miller,py might have bug

### Description
satellite orbit is poltted like this
![Figure_1](https://github.com/ut-issl/s2e-core/assets/95670311/5baefbc4-9508-4034-b240-4c7c53a5b222)

The right and left ends are connected by a line.

### Conditions of occurrence
The hash in which the bug occurs is `7fc6df46`, and the log file is in [https://drive.google.com/drive/folders/1I6muwtwqflZkFgqWR3HTmSq4Mahy_4V5?usp=sharing]

**Comment by 200km** [comment]
@DaikiTsuzuki バグ報告ありがとうございます。
私の環境でも確認できました。  

[この資料](https://github.com/ut-issl/s2e-documents/blob/develop/General/HowToVisualizeSimulationResults.md)を作った時点ではこのバグはでていないようです。その後のこのscript関連の修正は、matplotlibなどのライブラリのバージョン更新だけなのでその辺りが怪しいかなと思っています。

**Comment by 200km** [comment]
linestyle=’None’　設定すれば解決する気はする。

**Comment by DaikiTsuzuki** [comment]
解決しました。ありがとうございます。

**Comment by 200km** [comment]
こちら、元コードの方も `linestyle=’None’`を入れるように修正しようと思うので、Reopenしました。

簡単な修正なので、研究室の新入メンバーにやってもらおうと思っているので少々お待ち下さい。

**Comment by 200km** [comment]
こののバグが発生するのは、次の2つ
- [plot_gs_visibility.py](https://github.com/ut-issl/s2e-core/blob/5edc3e5b8ad25477a8de06cdb503b52460440a52/scripts/Plot/plot_gs_visibility.py)
- [plot_satellite_orbit_on_miller.py](https://github.com/ut-issl/s2e-core/blob/5edc3e5b8ad25477a8de06cdb503b52460440a52/scripts/Plot/plot_satellite_orbit_on_miller.py)

それぞれの`map.plot(sc_map_lon[i], sc_map_lat[i], color='blue', marker='o', markersize=3)`などに`linestyle='None'`設定を入れるだけでと思っています。
担当割りは
- plot_gs_visibility.py -> @ogoogo 
- plot_satellite_orbit_on_miller.py -> @Hiro-0110 
でお願いします。
