### ISSUE TITLE
Decide Release rules

### ISSUE THREAD

**Issue by sksat** [ut-issl/s2e-core#53]
## Overview
Decide rule about how to release/update S2E.

## Details
- [ ] versioning: (semver?)
- [ ] update rule
- [ ] document rule

## Conditions for close
When xxx is complete.

## Supplement
N/A

## Note
- If there are related Projects, tie them together.
- Set `priority` label if possible.
- Assignees should be set if possible.
- Write a conclusion when closing the issue.

**Comment by sksat** [comment]
バージョニングに関してはsemver(的運用)でよいと思います．C2Aもそうなりましたし(https://github.com/ut-issl/c2a-core/issues/141)．

**Comment by sksat** [comment]
問題はどのようにバージョンを上げていくかなんですよね．もちろん「これは大きな更新だな」という時に(気分で)major versionを上げるとかも全然いいんですけど，S2E coreの後方互換性ってどう考えたらいいのか，という．

**Comment by sksat** [comment]
C2Aのcore部もcoreというよりかはライブラリ的側面が強いけれど，S2Eはこれがもっと強い．どのくらい強いかというとS2E userは実態としてはS2E coreのforkという認識をした方がよい．

**Comment by sksat** [comment]
で，本題なんですが，色々整理すると，「S2Eの互換性はcore/userで考えるべきではなく，**各コンポーネント**から**他のコンポーネント**とユーザコードに対して考えるべき」，というのが個人的な結論です．
文脈としては以下
- S2E userは実態としてはS2E coreのfork
- S2E coreは(現状はかなり密結合になっているが)各コンポーネントをまとめたmono-repoとして捉えるのがよい
  - このmonorepoには`src/S2E.cpp`などの **exampleとしてのユーザコード** も入っており，単体でビルドすることもできる

**Comment by sksat** [comment]
あっ放置しててすみません．少なくとも形式上はsemver(`<major>-<minor>-<patch>`)でやる，ということで合意が取れていればよく，ドキュメントというかREADMEにそういう旨を書いておく，というぐらいですかね．あと既存バージョンのリリースをするならそれも．

**Comment by 200km** [comment]
> 少なくとも形式上はsemver(<major>-<minor>-<patch>)でやる

これで進めてOKだと思います！

> ドキュメントというかREADMEにそういう旨を書いておく

僕の方で書いていいと思いつつ、どんなふうに書けばよいかいまいち分かっていないので、やっていただけると嬉しいです。

> あと既存バージョンのリリースをする
これはあまり深く考えずに2.0~4.0をreleaseだけするという感じでいいですかね？

**Comment by sksat** [comment]
了解です．
既存バージョンのリリースはやるだけで大丈夫です．ただしせっかくなので`2.0.0`ということにしてもいい(`2.0`とかはエイリアスということにして)かな，ぐらいの気持ちです．

**Comment by 200km** [comment]
わかりました。2.0.0にしておきます~

**Comment by sksat** [comment]
既存のバージョンに対してpatch version付きのタグ追加 & GitHub Releaseでのリリースが行われた
- https://github.com/ut-issl/s2e-core/releases/tag/v2.0.0
- https://github.com/ut-issl/s2e-core/releases/tag/v3.0.0
- https://github.com/ut-issl/s2e-core/releases/tag/v4.0.0

**Comment by sksat** [comment]
READMEにも書いたので閉じ
