### ISSUE TITLE
Fix port closing

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/s2e-core#66]
## Overview
1.  The SILS port of the I2C emulated components is not closed properly.
2. If the CommunicationBase class is copied, double freeing of memory can occur.

### Description
1. In the destructor of ObcI2cTargetCommunicationBase for SILS test, the function `CloseComPort` for UART is used when the function `I2cCloseComPort` for I2C should be used.
2. In UART and I2C CommunicationBase, memory is freed in the destructor. If CommunicationBase class is copied, double freeing of memory can occur.
### Conditions of occurrence
1. This occurs when performing a SILS test with I2C emulated components.
2. This happens when the UART or I2C CommunicationBase class is copied.
###  Additional information
files, link, etc, if any.

## Task
- [x] Fix destructor in ObcI2cTargetCommunicationBase
- [x] Add copy constructor

## Scope of influence
The behavior of CommunicationBase will be change.

## Supplement
NA

## Note
- Write a conclusion when closing the issue.

**Comment by 200km** [comment]
対応PRがマージされたのでCLOSEします。
