### ISSUE TITLE
Add orbit interpolation method as an Orbit calculation feature

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#664]
## Details
We need a satellite orbit calculation method using interpolation with orbit time series input.  
We already have a basic function as follows.

https://github.com/ut-issl/s2e-core/blob/develop/src/math_physics/orbit/interpolation_orbit.hpp

## Closing conditions
The feature is implemented,

## Supplementary information
NA

## Note
- Provide a conclusion before closing the issue.

**Comment by fukudakazuya** [comment]
@200km こちらのタスクの意図としてはTrigonometric以外の手法を追加するということでよろしいでしょうか？

**Comment by 200km** [comment]
ライブラリは準備しているのでそれを使って次のような機能を実装します。

- 現在様々な軌道伝搬手段で衛星軌道伝搬ができるが、それに「軌道定義ファイルを入力し伝搬する」という機能を付け加える
- 軌道定義ファイルの性格上、必ず内装が必要なので、ライブラリの内装機能を使って実装する
- 軌道定義ファイルとしては標準という意味ではSP3が良いように思うが、もっと単純なCSVファイルでもよく、そこは川端さんなど利用者側と相談する

**Comment by fukudakazuya** [comment]
かしこまりました．ありがとうございます．
こちら新しいファイルに実装するのが良いでしょうか？

**Comment by fukudakazuya** [comment]
@200km 追加で質問です。軌道定義ファイルで時系列データを読み込んで、それを内挿で補間していくという理解でよろしいでしょうか？伝搬と聞いてRK4などで伝搬するのかなと思ったのですが、今回はそういう意味ではない感じでしょうか。

**Comment by 200km** [comment]
> こちらどこに実装するのが良いでしょうか？

ソースコードとしてはこの場所が良いと思います。
https://github.com/ut-issl/s2e-core/tree/develop/src/dynamics/orbit

> 軌道定義ファイルで時系列データを読み込んで、それを内挿で補間していく

はい。漢字間違っていましたが内装とかいていたのは内挿のことです。

> RK4などで伝搬するのかなと思ったのですが、今回はそういう意味ではない感じでしょうか。

有力ファイルには推進計操作なども含んだものになるので、RK4などは適しません。なので、新たな軌道伝搬方法（計算方法）を追加するということです。

**Comment by 200km** [comment]
GNSS衛星の軌道計算をSP3ベースでやっている部分など参考にしてください。

https://github.com/ut-issl/s2e-core/blob/562acf9e4f7a51ffb3b3e0560a423ecc093bbcc0/src/environment/global/gnss_satellites.hpp#L116

**Comment by fukudakazuya** [comment]
![interpolate](https://github.com/user-attachments/assets/a9e16004-0455-4d93-9e64-4e53a5a17e10)
![interpolate_big](https://github.com/user-attachments/assets/5251027c-5e05-4ef7-adca-fd06568e9d2f)
