### ISSUE TITLE
Decide line length settings of clang-format

### ISSUE THREAD

**Issue by seki-hiro** [ut-issl/s2e-core#70]
## Overview
Decide line length settings of clang-format

## Details
In Google C++ Style Guide, the [maximum line length](https://google.github.io/styleguide/cppguide.html#Line_Length) is 80 characters. In some situations, more than 80 characters may be desirable.

## Conditions for close
The line length settings of clang-format is decided.

## Supplement
[Related thread](https://github.com/ut-issl/s2e-core/pull/69#discussion_r834266183)

## Note
NA

**Comment by 200km** [comment]
@sksat [こちら](https://github.com/ut-issl/s2e-core/pull/69#discussion_r835733422)の議論にあるように、文字数制限を少し増やせたら嬉しいなと思っているのですが、いかがでしょう。

C2Aの方は130文字くらいまで許しているかと思います。

**Comment by sksat** [comment]
返事が遅くなってすみません！1行の文字数制約は増やしていいと思います(あくまで統一されていることが大事なので)

**Comment by 200km** [comment]
ありがとうございます。では、文字数はC2Aと合わせようと思います。

**Comment by sksat** [comment]
了解です．C2Aの方は100文字なんですかね？TBDとなってますが
https://github.com/ut-issl/c2a-core/blob/develop/Docs/General/coding_rule.md#%E6%94%B9%E8%A1%8C%E3%81%AA%E3%81%A9-w-f

**Comment by 200km** [comment]
https://github.com/ut-issl/c2a-core/blob/4805eb3e3f352365f255e8674479c14fa19ca1f8/Script/CI/check_coding_rule.py#L279


150文字見たいですね。

**Comment by sksat** [comment]
お，なるほど

**Comment by sksat** [comment]
とりあえず150文字でPR出しました
