### ISSUE TITLE
Update to use VS2022 as default

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#77]
## Overview
Update to use VS2022

## Details
VS2019 will be unsupported soon.  
https://docs.microsoft.com/ja-jp/lifecycle/products/visual-studio-2019  
- Batch files for external libraries should be deprecated
- `CMakeSettings.json` should be modified

## Conditions for close
- Check build and execution in VS2022.

## Supplement
NA

## Note
NA

**Comment by hoshika-mas** [comment]
4/12が期限なのはVer16.7なんで急ぎではないですが、今となっては新規にVSダウンロードする際は2022の方が楽。
s2e-core/scripts/VisualStudio/make_nrlmsise00_VS32bit.batの
`Please chose your VS version (2017 or 2019):`
周辺も直しておいた方が良いかもしれません。
