### ISSUE TITLE
Delete warnings

### ISSUE THREAD

**Issue by 200km** [ut-issl/s2e-core#87]
## Overview
Delete warnings

## Details
There are so many warnings in S2E build. We need to delete them.

## Conditions for close
- [x] all warnings are deleted.

## Supplement
NA

## Note
NA

**Comment by 200km** [comment]
#92 と #93　でだいぶ減った。残りもう少し頑張る。

**Comment by 200km** [comment]
@sksat 外部からコピーしてきているコードのwarningも気にせず修正していっていいですかね？

**Comment by 200km** [comment]
#97 ここまでのPRがすべて通れば、g++のwarningsはなくなるはず。  
Windows Visual Studio側も確認が必要。

**Comment by sksat** [comment]
> @sksat 外部からコピーしてきているコードのwarningも気にせず修正していっていいですかね？

いいと思います

**Comment by 200km** [comment]
@sksat 外部からコピーしてるコードに `#pragmra warning`を使っているものがありました。このあたりどうしましょうか。

**Comment by 200km** [comment]
VS2019でビルドしたら、111件warningがでた。。。  
VSとg++で警告オプションのレベルを似たものにしたいですね。

**Comment by 200km** [comment]
現状整理
- g++
  - 警告オプションは [-Wall](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)
  - #pragma warningしているよwarning以外は消えた
- VS2019
  - 警告オプションは [/W4](https://docs.microsoft.com/ja-jp/cpp/build/reference/compiler-option-warning-level?view=msvc-170)
  - 111件のwarning

**Comment by 200km** [comment]
@sksat ワーニングの件、アドバイスいただけると嬉しいです。  
方針として、
1. VS側の警告レベルを下げてg++に合わせる
2. g++側の警告レベルを上げてVSに合わせる
3. いまの警告レベルのままでとにかくVS側もwarningを削る

の三択で、2が一番良いのだろうなと思いつつ、警告レベルの設定をよく理解しておらずどうしようかなと言う感じです。

**Comment by sksat** [comment]
とりあえずg++に`-Wextra`を追加かな，と思います(GCCは`-Wall -Wextra`してようやくほぼすべてのワーニングが出るので)．

**Comment by 200km** [comment]
Thanks. I agree with you.

**Comment by 200km** [comment]
After we added the `-Wextra`, we can see 1300 warnings in g++...  
I will tackle to delete them all.

**Comment by 200km** [comment]
@sksat There are so many `unused parameter` warnings for function's arguments.  
Can I use `UNUSED` macro like [here](https://stackoverflow.com/questions/3599160/how-can-i-suppress-unused-parameter-warnings-in-c)?  
Or do you have an another recommendation?

**Comment by sksat** [comment]
`UNUSED`マクロはせっかく出ているワーニングを握り潰すということなので，あんまりやりたくはないですね...
これは他のuserとかから使われていて変更のためのコストが大きい，そもそも後から引数を使うように実装が変わる可能性がある，ということですかね？

**Comment by 200km** [comment]
> これは他のuserとかから使われていて変更のためのコストが大きい

Yes, changing the function's arguments makes huge effect to all users. But if it is really need to change, I can change it.

> そもそも後から引数を使うように実装が変わる可能性がある
There are several examples we cannot remove the arguments
- We use the arguments in HILS mode.
  - https://github.com/ut-issl/s2e-core/blob/develop/src/Interface/HilsInOut/HilsPortManager.cpp#L9
- Abstract class has the arguments, but some inheritance classes don't use the arguments
  - https://github.com/ut-issl/s2e-core/blob/develop/src/Component/AOCS/Gyro.cpp#L15

**Comment by sksat** [comment]
なるほどです．じゃあ仕方ないですかね．
ワーニングを握り潰すとはいっても`UNUSED`で握り潰している箇所を明示はできるわけですし，一旦`UNUSED`でやりましょう．

**Comment by 200km** [comment]
Thanks. I will make another issue to remove `UNUSED`.

**Comment by 200km** [comment]
All warnings are deleted again for g++ by #106.

**Comment by 200km** [comment]
We still have 57 warnings in VS2022.
![image](https://user-images.githubusercontent.com/19573779/164887199-5460c9c9-64e1-4fc7-a732-ccf196e2e654.png)

@sksat gcc側にもう少し警告オプション追加する必要がありそうですが，どれを入れるべきかというのが分かっておらず，教えてもらえると嬉しいです．

**Comment by 200km** [comment]
とりあえずVS2022を使ってこれらのwarningsを消していきます．

**Comment by 200km** [comment]
@seki-hiro I2cObcTarget周りでHILS用に追加実装してくれた部分で，uint/int関連のワーニングが出ているので修正してもらえますか？いろんな関数が関連していて，実装者本人にやってもらった方が正確そうなので．

**Comment by 200km** [comment]
[この記事](https://qiita.com/MitsutakaTakeda/items/6b9966f890cc9b944d75)のオプション設定を参考にしたりすると良いのでしょうか？

**Comment by 200km** [comment]
g++について上の記事のwarning設定にしてみたところ、次のような感じになった。  

> 何もwarningが出なかったもの

-Wcast-align -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wlogical-op -Wmissing-include-dirs -Wnoexcept -Wredundant-decls -Wsign-promo -Wstrict-null-sentinel -Wundef -Wno-unused

> warning出たもの

- -pedantic : +1k
- -Wcast-qual : +4
- -Wformat=2 : +1
- -Wmissing-declarations : +14
- -Wold-style-cast : +298
- -Woverloaded-virtual : +4
- -Wshadow : +26
- -Wsign-conversion : +2k
- -Wstrict-overflow=5 : +15
- -Wswitch-default : +1

ただ、Visual Studioと同じようなwarningが出ているようには見えなかった。表示が違うだけで一緒なのかもしれないけれど。

**Comment by sksat** [comment]
ワーニングというのはコンパイラがそれぞれかなり独自に出しているものなので，規格に絡むもの以外は他のコンパイラ実装でまったく同じものが出るということはないです(なんだかんだ似ていることはありますけどね)．とりあえず最優先で入れるべきなのは`-Wpedantic`かな(`-pedantic`と同じ意味です)．

**Comment by sksat** [comment]
`-Wsign-conversion`もまあ必要だな(というかそんなに出るのか)

**Comment by 200km** [comment]
完全に一致するとは思っていないのですが、似たwarningsが出てくれれば、一方で消せば他方も消えるので嬉しいなと思っていました。最終的にはどちらも見て、一方で出てたら修正するしか無いという感じですかね。  

とりあえず、VSで出ないようにします。

**Comment by 200km** [comment]
`-Wpedantic`　と　`-Wsign-conversion`　はその後入れるのを検討しますね。  
前者は変なところに`;`がついている、後者は配列の要素指定にintを使っているというのがほとんどだったので、修正できるかなとは思っています。

**Comment by sksat** [comment]
ですねー．両方見るしかないです．あーやけに多いなと思ったらそういうことか．なるほど．

**Comment by 200km** [comment]
残っているwarnings
> g++
- `#pragma warning`関連

> VS2022
- algorithm/transformを使っている`IniReader.cpp`
- defaultlib `LIBCMT` conflicts with use of other libs; use /NODEFAULTLIB:library

**Comment by 200km** [comment]
残りは`g++の#pragma warning関連`のみ。

**Comment by 200km** [comment]
#pragma warning関連 も片付けた。これで、一旦VS2022でもgccでもwarningは撲滅できた

**Comment by 200km** [comment]
`-Wpedantic`については、入れ込めてwarningも全部消した。動作に影響が出るような修正ではなかった。  
`-Wsign-conversion`は入れ込むの大変そう。

**Comment by 200km** [comment]
> `-Wsign-conversion`は入れ込むの大変そう。

入れようと思うと結構大きな改修になるので、v5.0.0に入れれそうにない。  
下記issueで別対応とする。  
https://github.com/ut-issl/s2e-core/issues/120
